#OPERADORES DE IDENTDADE
#OS OPERADORES DE IDENTIDADE SÃO USADOS PARA COMPARAR OS OBJETOS, NÃO SE FOREM IGUAIS, MAS SE FOREM REALMENTE
#O MESMO OBJETO, COM A MESMA LOCALIZAÇÃO DE MEMÓRIA

#1. IS(RETORNA TRUE SE AMBAS AS VARIÁVEIS FOREM O MESMO BJETO
#2. IS NOT(RETORNA TRUE SE AMBAS AS VARIÁVEIS NÃO FOREM O MESMO OBJETO)

String_01 = 'Olá mundo!'
String_02 = "Olá mundo!"

print(type(String_01) == type(String_02))
print(type(String_01) is not type(String_02))
