#7º COMANDO ROUND
#QUANDO SE TRABALHA COM PONTOS FLUTUANTES, PODEMOS ARREDONDAR O VALOR USANDO UM COMANDO NATIVO DO PYTHON
#ROUND(VALOR, NÚMERO DE CASAS)


#COMANDO ROUND
valor_exemplo = 12.12121517189

print( round(valor_exemplo, 2))